FROM quantconnect/lean:10291

USER root

# add docker
RUN apt-get update \
    && apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

RUN apt-get update \
    && apt-get -y install docker-ce \
    && rm -rf /var/lib/apt/lists/*

# add rider
ADD https://download.jetbrains.com/rider/JetBrains.Rider-2020.3.2.tar.gz /opt/rider.tar.gz

RUN tar --extract --verbose --directory /opt --file /opt/rider.tar.gz && rm -f /opt/rider.tar.gz

USER unprivileged
